
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: regionalpd-storageclass
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard
  replication-type: regional-pd
# allowedTopologies:
#   - matchLabelExpressions:
#       - key: failure-domain.beta.kubernetes.io/zone
#         values:
#           - us-central1-a
#           - us-central1-b
#           - us-central1-c
#           - us-central1-f
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pv-db-edfi-admin-security
spec:
  storageClassName: regionalpd-storageclass
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pv-db-edfi-ods-2021
spec:
  storageClassName: regionalpd-storageclass
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pv-db-edfi-ods-2022
spec:
  storageClassName: regionalpd-storageclass
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
